[providers.python]
version = "3.13"

[phases.setup]
aptPackages = [
    "wget",
    "unzip",
    "gnupg",
    "libnss3",
    "libgconf-2-4",
    "libfontconfig1",
    "xvfb",
    "gconf-service",
    "ca-certificates",
    "fonts-liberation",
    "libasound2",
    "libatk-bridge2.0-0",
    "libnspr4",
    "libxcomposite1",
    "libxkbcommon0",
    "libxrandr2"
]
commands = [
    "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y google-chrome-stable",
    "rm -rf /var/lib/apt/lists/*",
    "CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)",
    "wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip",
    "unzip chromedriver_linux64.zip",
    "chmod +x chromedriver",
    "mv chromedriver /usr/local/bin/"
]

[config]
environment = { 
    GOOGLE_CHROME_BIN = "/usr/bin/google-chrome",
    CHROMEDRIVER_PATH = "/usr/local/bin/chromedriver",
    DISPLAY = ":99"
}

[phases.start]
command = "uvicorn main:app --host 0.0.0.0 --port 8000"